### PR TITLE
Formatting & Partitioning tasks

### PR DESCRIPTION
**Pull request by nmcspadden**
"eraseVolume" and "partition" tasks now added as workflow tasks for config_imagr.plist.

### CODE REVIEW

**Comment by grahamgilbert** [comment]
Some documentation in the PR on the options that can be used would be good, as would updating the validation tool so I know if I'm putting in something stupid.

**Comment by nmcspadden** [comment]
@grahamgilbert How do you want this documented?  Seems forking doesn't include wiki pages.

**Comment by grahamgilbert** [comment]
Just in the pull request is fine for now. Just so I know what I'm testing!

Graham Gilbert

**Comment by nmcspadden** [comment]
@grahamgilbert Added testing documentation.

**Comment by grahamgilbert** [comment]
Thanks, I'll play with it today / tomorrow, but I'm off on wedding / honeymoon on Friday, so if I don't merge by then, it will be June 10th before I'm back in the saddle.

**Comment by grahamgilbert** [comment]
In my quick testing this looks good to me. Please add the documentation to the wiki and then I'll remove your notes to keep things clean (if I get more internet, it's sporadic access here to put it kindly!).

**Comment by nmcspadden** [comment]
Wiki has been updated.

On Mon, Jun 1, 2015 at 1:56 AM, Graham Gilbert notifications@github.com
wrote:

> In my quick testing this looks good to me. Please add the documentation to
> the wiki and then I'll remove your notes to keep things clean (if I get
> more internet, it's sporadic access here to put it kindly!).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/grahamgilbert/imagr/pull/83#issuecomment-107372560.

## 

## 

Nick McSpadden
nmcspadden@gmail.com

**Pull request merged**
