### PR TITLE
Move AutoNBI arguments to a variable

### PR DESCRIPTION
**Pull request by clburlison**
As new options/features are added to AutoNBI we shouldn't need to modify Imagr to support these features.

### CODE REVIEW

**Comment by kcrawshaw** [comment]
This seems to fail when I run the Makefile. ARGS variable is passed as one string instead of individual args.
`sudo ./AutoNBI.py "-e -p" -s "/Applications/Install OS X Yosemite.app" -f Packages -d ~/Desktop -n "Imagr"`

**Comment by clburlison** [comment]
@kcrawshaw if you are running the AutoNBI command by itself you do not need to quote the arguments. This pull request for the makefile will allow you to pass arguments via the make command
 IE: `make nbi ARGS="-e -p" OUTPUT=~/Desktop`

**Comment by kcrawshaw** [comment]
@clburlison I forgot to mention, that was part of the output from running `make nbi URL="http://my_server/imagr_config.plist"`

If I modify `ARGS= "-e -p"`  to `ARGS = -e -p` in the Makefile it will run successfully. `-e -p` does not need to be in quotes, at least from what I'm seeing. Does it run fine for you?

**Comment by clburlison** [comment]
You are correct the default behavior of Make is to pass the variable as a quoted string. My mistake for not testing both cases. I'll issue a new pull request.

**Pull request merged**
