### PR TITLE
added enough logic to not do anything if script url fails to download

### PR DESCRIPTION
**Pull request by chilcote**

### CODE REVIEW

**Comment by grahamgilbert** [comment]
I think I'm going to refactor this so we get an error message - this will mean determining whether it's a url or not further down. Since the code works at the moment (if the URL is perfect, obviously!), I don't think I should merge this in.

**Comment by chilcote** [comment]
Is it a matter of adding in methods similar to the package download methods? I can work on this if you want. Don't want to be in the habit of creating more work for you due to a half-assed pr.

**Comment by grahamgilbert** [comment]
Yep, the code would look very similar to that. 

Graham Gilbert

**Comment by chilcote** [comment]
OK I'll mess around with it this evening.

**Pull request closed without merging**
