### PR TITLE
Add background image

### PR DESCRIPTION
**Pull request by MagerValp**
This allows you to specify a `background_image` URL in `imagr_config.plist` to hide the ugly gray boot screen. If you no image is specified it displays a grim and colorless gray, with all joy removed.

I'll update the wiki docs if you merge.

### CODE REVIEW

**Comment by gregneagle** [comment]
Question/concern:

On my main test machine at least, when I try to open another utility (Startup Disk, Terminal, etc) it opens behind the Imagr window and I have to move the window to find the other utility's window and click it to bring it forward. (I feel like this is a regression -- that early in Imagr's development I worked on fixing that...) Anyway, I worry that this new backdrop window will obscure the other app's windows, and I won't be able to bring them forward.

Maybe this https://github.com/grahamgilbert/imagr/pull/136/files#diff-ce68cf9796c9e079990a9fc6625e860cR169 deals with that potential issue?

**Comment by MagerValp** [comment]
That's definitely a regression. Can you see if it's better now? I just left work and can't test from an nbi until monday.

**Comment by grahamgilbert** [comment]
Will test this on Tuesday. Am away until then. 

Sent from my iPhone

On Fri, May 13, 2016 at 8:59 AM -0700, "Per Olofsson" notifications@github.com wrote:

That's definitely a regression. Can you see if it's better now? I just left work and can't test from an nbi until monday.

**Comment by MagerValp** [comment]
This took a bit of work to fix, and it's doubly annoying that I can only reproduce it when booted from an nbi, not when testing in Xcode or running from the desktop. Anyway, the root cause seems to be that LaunchServices isn't running properly, but since fixing that is above my pay grade I made the code to activate after launching a little more aggressive. @gregneagle please try again, it seems to work well for me now.

Regarding the background window covering other apps, that was my worry too, but the solution was to send it to another plane of existence with `setLevel:`. This puts the window in the same category as the desktop, and it can never appear on top of application windows.

**Comment by erikng** [comment]
I've tested this branch and it seems to work well. The utilities are not hidden.

**Comment by grahamgilbert** [comment]
I'm building an nbi to test this out now, but would it be possible to add in a check to `validateplist`? Basic things like it must be a string, must start http or https etc.

**Comment by MagerValp** [comment]
Yes, but I'd have to rebase on top of the other changes to avoid merge conflicts, and I'm not sure how that would affect this PR. I can either commit here and let you deal with the merge, or I can file a separate PR with the `validateplist` changes.

**Comment by grahamgilbert** [comment]
Separate PR is fine, I'm going to merge this now, it looks great!

**Comment by macmule** [comment]
Hey folks,

Wasn't paying my attention to this. But shouldn't the tool creating the image should really be set by the tool that creates the NetInstall/NetBoot/OS set the background?

AutoImagrNBI has an option for this, but it's then overridden by the Imagr.app.

Personally I'd have the OS environment creation tool set the background. 

But if this function is put into release, I'll probably can the option to set desktop background in AutoImagrNBI & instead set it to the grey. 

So only folks with a custom set desktop from Imagr will then see the desktop image change when Image loads.

**Comment by grahamgilbert** [comment]
I don't agree. This will make it easier for people to set a background without using a third party tool. Imagr really is designed to be run an AutoNBI environment. If you feel that strongly about it, I would accept a PR for a local preference key to disable this.

**Comment by macmule** [comment]
If this is not a desktop image, but an image overlaying the background.. Then folks will need to quit Imagr to see their desktop. 

Things like seeing mounted disks will require Imagr.app closed.

**Comment by macmule** [comment]
As mentioned on Slack, how about Imagr not displaying the background if Finder or Dock is running?

**Comment by MagerValp** [comment]
I filed issue #143 to deal with this conflict.

**Pull request merged**
