### PR TITLE
Get Existing HostName

### PR DESCRIPTION
**Pull request by vmiller**
- With this change, Imagr will attempt to read the HostName from the target volume and populate the computer name field with it.
- Also, it the 'auto' key is used without the 'use_serial' key it will automatically assign the existing name (if it exists).

### CODE REVIEW

**Comment by grahamgilbert** [comment]
Can you document this new behaviour in the wiki if you haven't already?

**Comment by vmiller** [comment]
Yes, I'll add to the wiki for this.

**Comment by gregneagle** [comment]
Is this task ordering sensitive? IOW, is it important/required to add this to the workflow before any imaging step (I'm guessing yes) If so, be sure to document...

**Comment by grahamgilbert** [comment]
Yes, it is. It's just a wrapper around a first boot script.

**Comment by gregneagle** [comment]
Not sure that actually clarifies things for me. For example, no matter where I put the current machine naming task in the workflow, the UI appears before any imaging step runs.

**Comment by grahamgilbert** [comment]
Yes, but the first boot script task happens later in the correct order.

**Comment by gregneagle** [comment]
That's great. I think the documentation should make that clear.

**Pull request merged**
