### PR TITLE
adding option for scripts to be defined as URLs in the config plist i…

### PR DESCRIPTION
**Pull request by chilcote**
…nstead of a string containing the contents of the script.

### CODE REVIEW

**Comment by grahamgilbert** [comment]
This looks good. Can you update validateplist so it will accept script components with a url?

**Comment by grahamgilbert** [comment]
I'll do it myself, I'm being lazy!

**Comment by chilcote** [comment]
If you don't have time I'll get to it in the morning. You should be on vacation!

**Comment by grahamgilbert** [comment]
I've done it and pushed, but if you've not done it already, can you
document it on the wiki (noting that it's only in the dev version and not
in the release currently)?

**Comment by chilcote** [comment]
Yep will do. Cheers!

**Comment by clburlison** [comment]
Didn't realize that was such a small code change. Thanks @chilcote. Also, I updated the wiki https://github.com/grahamgilbert/imagr/wiki/Workflow-Config#scripts

**Comment by gregneagle** [comment]
How horribly does Imagr blow up if the script is not available at the url during workflow execution time?

**Comment by grahamgilbert** [comment]
I'd imagine it's pretty messy. I'm adding some error checking next week. Once again, most of this can be solved lifting code from package downloading.

Graham Gilbert

**Comment by chilcote** [comment]
Not full error checking, but I added a few lines so it will not do anything if the url fails. https://github.com/grahamgilbert/imagr/pull/94

**Pull request merged**
