### PR TITLE
Added a shake to the window when the password is incorrect

### PR DESCRIPTION
**Pull request by tburgin**
Stole the idea from:

```
http://sourceforge.net/p/pyobjc/mailman/message/24491254/
```

### CODE REVIEW

**Comment by grahamgilbert** [comment]
Looks good. I'm sure you've checked, but is quartz in an autonbi image?

**Comment by tburgin** [comment]
Ah, have not looked...Let me check.

**Comment by clburlison** [comment]
Quartz is present. I already had a test running.

**Comment by tburgin** [comment]
Sweet. Quartz is also present in Deploy Studio

**Pull request merged**
