### PR TITLE
Added config.mk so you can override the defaults in Makefile without cluttering up git

### PR DESCRIPTION
**Pull request by natewalck**
This should make it easier to update in the future with a simple git pull (config.mk is in gitignore so it won't require a git merge).

### CODE REVIEW

**Comment by natewalck** [comment]
Argh, this PR got mixed with another newer commit. Ooops!

**Comment by grahamgilbert** [comment]
Fancy wiring up the menu bar items to do the same? One for Disk Utility and one for Terminal :)

**Comment by groob** [comment]
Would it be possible to add the Firmware Password Utility as well? It's one we use a lot, and also included in DS and in the recovery partition.

**Comment by natewalck** [comment]
@groob That would be an AutoNBI thing rather than an Imagr thing. Perhaps a request over on https://bitbucket.org/bruienne/autonbi

**Comment by gregneagle** [comment]
No - his point is the app is in /Applications/Utilities - he wants Imagr to be able to open it.

**Comment by natewalck** [comment]
Ah, I was thinking it wasn't present.

That is a valid request. Cut a new issue for it so we can keep this one cleanish.

**Pull request merged**
