### PR TITLE
first try at a Makefile

### PR DESCRIPTION
**Pull request by groob**
I created a Makefile to help with building and testing.

`make` builds Imagr.app
`make deps` grabs the dependencies(autonbi and munkitools)
`make netboot` creates a new netboot image.
`make clean-all` lets you start over with AutoNBI and Packages Directory empty.

### CODE REVIEW

**Comment by grahamgilbert** [comment]
Looks good, but is there any way we can generate `com.grahamgilbert.Imagr.plist` as well?

**Comment by clburlison** [comment]
I've got this one covered. @groob look for a pull request from me later tonight. Need to write the documentation up. I didn't know you could have variables in Makefiles...

This doesn't have a GUI but does address #22  

Example command:

`make netboot URL="http://my_server/my_config.plist" OUTPUT=/Volumes/data/tmp`

**Comment by groob** [comment]
@grahamgilbert, @clburlison I've been thinking about the best way to add `https://groob@bitbucket.org/whitbyschool/autopkg-overrides.git`. One option is to add it to `.gitignore` and let the user create their own.   The other option is to commit the default one with $SERVER_URL set to `http://imagr/imagr_config.plist`

We can also generate one and have the user overwrite the SERVER_URL using an environment variable.

**Comment by groob** [comment]
@grahamgilbert updated the pull request with the changes from @clburlison. The makefile now includes the configuration plist.

**Comment by grahamgilbert** [comment]
I really like this, excellent work. I've been thinking though, there are some poor souls who don't use Munki and probably won't fancy having a Munki install left on their machine. I'm thinking it would be better to just curl down FoundationPlist.py - AutoNBI will pick it up if it's in the current working directory.

**Comment by gregneagle** [comment]
I've suggested to bruienne that he should just include FoundationPlist with AutoNBI to eliminate the dependency on Munki.

**Comment by groob** [comment]
I'm all for vendoring dependencies.

The `make nbi` command will now use curl to get FoundationPlist if it's not available.

**Pull request merged**
