### PR TITLE
add imagrlib and reference points

### PR DESCRIPTION
**Pull request by erikng**
This should help out as more features are added.

### CODE REVIEW

**Comment by gregneagle** [comment]
A little confused as to the motivation/point here. I certainly don't think the AppDelegate and MainController should be moved into a subfolder -- they are the most important files in the project.

What's the overall goal here?

**Comment by erikng** [comment]
I'm going to work on a tool (stealing your work mostly) and I have a feeling as more features are added, it might make sense to start organizing the base functions.

**Comment by gregneagle** [comment]
It might. But moving the main application objects is not a good idea, as it breaks expected patterns. Seems like maybe this should be discussed, then implemented... (but obviously all up to Graham)

**Comment by erikng** [comment]
Not a problem. I did it figuring there would be a discussion anyway.

**Comment by grahamgilbert** [comment]
I'm not convinced this is a good idea. Besides, this only affects the code before it's built in Xcode - everything is dumped into one directory when the app is built: https://www.dropbox.com/s/vp7nd3jnvpz1fqi/Screenshot%202015-04-25%2009.46.49.png?dl=0

I need more convincing if we're going to do this.

**Comment by gregneagle** [comment]
"everything is dumped into one directory when the app is built" -- that's Xcode's default behavior, but one _can_ make custom build phases with custom file copy tasks that copy things to different folders.

But, I too, am not convinced that doing this is important.

I think you'll eventually want to "slim down" what is included: getting rid of all of the gmacpyutil *_test.py files, and any unused files from that project, but that's a different discussion.

**Comment by erikng** [comment]
Here's some more reasoning (based on my own likes/desires). In my testing I am treating it similarly to munki.

Imagr Repo:
imagr_config.plist
workflows
masters
packages
scripts

imagr_config.plist should be treated similarly to munki's catalogs (automatically generated). This way we can make a tool like "importworkflow/makeworkflow" where an admin can specify his parameters and create a new workflow from command line. This can also support "included_workflows". Running another tool "makeconfig" would then automatically add the workflows to the imagr_config.plist.

This is just my vision and perhaps it doesn't match what everyone else sees. But if we do agree on this, then it would be smart to start putting this in a library. Copying again from munki, we can make a separate Imagr.app pkg from the admin tools pkg (if desired by the admin).

**Comment by grahamgilbert** [comment]
But wouldn't make config just concatenate individual workflow plists? Beyond making a GUI tool eventually to make workflow, that's all I'm considering at the moment.

**Comment by erikng** [comment]
That depends on how we define included_workflows. included_workflows might be tagged "hidden".

**Comment by gregneagle** [comment]
I don't see much overlap in the code required to build and manage config plists and the code in Imagr.

**Comment by natewalck** [comment]
gpmacpyutil should stay its own standalone library as it is an external dependency from Google. This leaves Utils and gurl.py. Utils can be grabbed and used by itself if necessary just as gurl.py was grabbed from Munki.

I do think that gurl and foundationplist could be made into a pip package and maintained on pip so they are easy to get into your projects, but I've not had time to make progress on that(yet).

**Comment by groob** [comment]
@erikng I started building a server side tool for myself, as I would also like to manage workflows separately from imagr_config.plist.

There needs to be a tool similar to makecatalogs from munki that builds individual workflows, but that's not necessarily a requirement for this repo.  It's likely that there are going to be many third party tools that manage workflows, similar to munki and reposado. 

What I think is more important for Imagr right now is to define a mechanism for stitching workflows together from individual files. I'd personally like to see each workflow in the plist have a UUID, similar to DeployStudio's workflows.

**Pull request closed without merging**
