### PR TITLE
Remote syslog

### LINKED ISSUE #98: syslog logging
We would love to be able to log from the imgr.app to a syslog server

### PR DESCRIPTION
**Pull request by rdrake**
When given a syslog URI in the following form, Imagr sends reports to a remote syslog server.

```
syslog://<hostname:localhost>:<port:514>/?transport=<transport:UDP>&facility=<facility:local7>
```

The result on the remote syslog server is similar to the following.

```
 Sep  8 09:38:36 <hostname> Imagr: [<serial>] Imagr is starting up...
 Sep  8 09:38:47 <hostname> Imagr: [<serial>] Preparing to run workflow <workflow>...
 Sep  8 09:38:48 <hostname> Imagr: [<serial>] Restoring DMG: http://<hostname>/osx_custom_150814-10.10.5-14F27.hfs.dmg
 Sep  8 09:40:24 <hostname> Imagr: [<serial>] Setting computer name to <serial>
 Sep  8 09:40:29 <hostname> Imagr: [<serial>] Downloading and installing package(s): ...
 Sep  8 09:40:46 <hostname> Imagr: [<serial>] Copying first boot script 6.0
 Sep  8 09:40:47 <hostname> Imagr: [<serial>] Finished running <workflow>.
```

This fixes #98.

### CODE REVIEW

**Comment by grahamgilbert** [comment]
This looks ok - I assume it's been tested in a 10.11 nbi?

**Comment by rdrake** [comment]
I have tested it in an NBI built from the 10.11.0 GM candidate (15A282a) and everything went smoothly.

**Comment by erikberglund** [comment]
I have added support for this setting in NBICreator for the next update, but as I could not find any documentation, I wanted to know if this is the format of the string that has to go into the 'syslog' key in com.grahamgilbert.Imagr.plist?

`syslog://<hostname:localhost>:<port:514>/?transport=<transport:UDP>&facility=<facility:local7>`

**Comment by grahamgilbert** [comment]
@rdrake can you update the wiki with the required info please?

**Pull request merged**
