### PR TITLE
Disable ATS for El Capitan

### PR DESCRIPTION
**Pull request by erikng**

### CODE REVIEW

**Comment by erikng** [comment]
Sorry for the typo!

**Comment by gregneagle** [comment]
Just an FYI: this is only needed if you build Imagr against the 10.11 SDK. (Not implying you should not make this change; just adding more background info)

**Comment by erikng** [comment]
Well this is needed for Imagr to work properly on a 10.11 NBI as well.

See #Imagr slack channel.

**Comment by gregneagle** [comment]
In my testing an app built against the 10.10SDK (or lower) can call gurl.py (or specifically the NSURLConnection methods) without triggering ATS while running under El Cap. It's the combination of running under 10.11 and being linked against the 10.11 SDK that brings ATS into play.

See #Greg's testing notes.

**Comment by erikng** [comment]
Odd. I'm building Imagr with 10.10 SDK on a Yosemite 10.10.5 machine with the latest public Xcode. 

I could not pull down the imagr_config.plist without this modification via a 10.11 AutoNBI using the el-cap branch. 

When did you last test? Bruienne and I didn't fix AutoNBI until yesterday.

**Comment by gregneagle** [comment]
"When did you last test?"

Weeks ago. Can easily test again today.

**Pull request merged**
